BEGIN TRAN REMOVEEMPTYORGS
DECLARE @ORGID UNIQUEIDENTIFIER;

SET @ORGID = 'A9215E9C-BA72-4FDA-A1FA-6E2E62D70B79';
 IF (SELECT COUNT(*) FROM USER_ORGANISATION WHERE ORGANISATION_ID =@ORGID)  = 0
    BEGIN
        DELETE FROM ORGANISATION_ASSOCIATION WHERE ORGANISATION_ID =@ORGID;
        DELETE FROM INVITATION_SERVICES WHERE ORGANISATION_ID=@ORGID;
        DELETE FROM INVITATION_ORGANISATION WHERE ORGANISATION_ID=@ORGID;
        DELETE FROM USER_ORGANISATION_REQUESTS WHERE ORGANISATION_ID=@ORGID;
        DELETE FROM [DBO].[ORGANISATION] WHERE ID=@ORGID;
    END

SET @ORGID = 'E7D479FD-2192-45C5-A9E6-E3F0EA231186';
 IF (SELECT COUNT(*) FROM USER_ORGANISATION WHERE ORGANISATION_ID =@ORGID)  = 0
    BEGIN
        DELETE FROM ORGANISATION_ASSOCIATION WHERE ORGANISATION_ID =@ORGID;
        DELETE FROM INVITATION_SERVICES WHERE ORGANISATION_ID=@ORGID;
        DELETE FROM INVITATION_ORGANISATION WHERE ORGANISATION_ID=@ORGID;
        DELETE FROM USER_ORGANISATION_REQUESTS WHERE ORGANISATION_ID=@ORGID;
        DELETE FROM [DBO].[ORGANISATION] WHERE ID=@ORGID;
    END
ROLLBACK TRAN REMOVEEMPTYORGS
